version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANNov17GitProject
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
